"use client";
import Link from "next/link";
import { Activity, ArrowRight, Check, FileText, Leaf, LockKeyhole, MessageCircle, Pill, Plus, ShieldCheck, UserRound } from "lucide-react";

export function Brand() { return <span className="ns-brand"><span className="ns-mark"><Plus size={21} strokeWidth={2.5} /></span>nutriti<span>scan</span><i>°</i></span>; }
const FEATURES = [
  { icon: MessageCircle, title: "Ask general health questions.", text: "The website chat is an early-access educational tool for general health questions. It does not diagnose, prescribe or retrieve a shared patient record.", tag: "Available · web chat", tone: "lime" },
  { icon: Leaf, title: "Keep a personal journal.", text: "The Android beta can save meals, health notes and conversations locally on your device. NutritiScan does not encrypt that local journal.", tag: "Available · Android beta", tone: "plain" },
  { icon: UserRound, title: "Prepare for a doctor visit.", text: "Use information you entered to organize questions and a factual visit summary. Review it yourself and let a qualified clinician interpret your health.", tag: "For clinician discussion", tone: "plain" },
  { icon: Pill, title: "Record medicines and allergies.", text: "The journal can keep notes you enter about medicines and allergies. It does not check interactions or recommend prescription changes.", tag: "User-entered notes", tone: "plain" },
  { icon: FileText, title: "Keep report tools in perspective.", text: "Private cloud report storage and automatic lab extraction are not active in this release. Do not rely on NutritiScan to interpret a lab result.", tag: "Not available yet", tone: "plain" },
  { icon: Activity, title: "Shared health records are not live yet.", text: "The cloud health workspace needs a deployed service. The dashboard shows its connection status; records do not currently sync to a NutritiScan account.", tag: "Not available yet", tone: "wide" },
] as const;

const FAQS = [
  {
    question: "What is NutritiScan?",
    answer: "NutritiScan is an early-access educational health companion. Its website offers general health chat, and its Android beta includes a local journal for meals, health notes and saved conversations.",
  },
  {
    question: "Can NutritiScan diagnose a condition or tell me which medicine to take?",
    answer: "No. NutritiScan does not diagnose, prescribe, recommend treatment or replace a qualified clinician. For urgent symptoms, contact local emergency services or seek urgent medical care.",
  },
  {
    question: "Can I upload a lab report and get a trend analysis?",
    answer: "Private report storage, automatic lab extraction and shared health-record trends are not active in the current release. Discuss your report with a qualified clinician.",
  },
  {
    question: "Where is my health journal stored?",
    answer: "Android journal entries are stored on your device and are not encrypted by NutritiScan. Web chat history and optional profile details can stay in your browser; messages are sent to the server when you submit them. Read the privacy notice before sharing health details.",
  },
  {
    question: "Does NutritiScan use patient records to train its models?",
    answer: "NutritiScan does not use patient records for model training. A chat message may be processed by a configured AI provider, so review its terms and avoid sharing information you are not comfortable sending.",
  },
] as const;
export default function ProductLanding() {
  return <div className="ns-marketing nl-root"><div className="nl-aurora" aria-hidden />
    <header className="nl-nav"><Link href="/" aria-label="NutritiScan home"><Brand /></Link><nav aria-label="Main navigation"><a href="#engine">Your health space</a><a href="#how">How it works</a><a href="#faq">FAQ</a><Link href="/privacy">Privacy</Link></nav><div className="nl-nav-actions"><Link className="nl-ghost" href="/health">Health dashboard</Link><Link className="nl-cta" href="/chat">Start a conversation <ArrowRight size={15} /></Link></div></header>
    <main><section className="nl-hero" id="top"><p className="nl-positioning">YOUR PERSONAL HEALTH COMPANION</p><span className="nl-badge"><i /> Educational early access · adults 18+</span><h1>Your health,<br />connected by <em>a conversation.</em></h1><p>NutritiScan is an early-access educational health companion. The website offers general health chat; the Android beta keeps meals, health notes and conversations in a local journal. Shared cloud records, private report storage, automatic lab interpretation and voice are not available in this release.</p><div className="nl-hero-actions"><Link href="/chat" className="nl-cta nl-cta-lg">Ask a general health question <ArrowRight size={17} /></Link><Link href="https://github.com/Adarsh-9182/nutritiscan/releases" className="nl-ghost nl-ghost-lg">Get the Android beta <ArrowRight size={16} /></Link></div><ul className="nl-trust"><li><Check size={13} /> Educational web chat</li><li><FileText size={13} /> Android journal beta</li><li><LockKeyhole size={13} /> Shared cloud records not live</li></ul>
    <div className="nl-preview" aria-label="Illustrative example of a health-record question"><div className="nl-preview-bar"><span className="nl-dot" /><span>Illustrative product workflow</span><span className="nl-preview-live">EARLY ACCESS</span></div><div className="nl-preview-grid"><div className="nl-thread"><div className="nl-ask">Mera hemoglobin ka trend kya hai?</div><div className="nl-reply"><div className="nl-avatar">+</div><div><div className="nl-steps"><span>Use confirmed history</span><span>Check dates and units</span><span>Show the source</span></div><p>When shared health records are available, NutritiScan is designed to show exact saved values and their sources. This workflow is an illustration; cloud records and report analysis are not live in the current release.</p><div className="nl-source"><ShieldCheck size={13} /> No values are fabricated in this example</div><small>Illustrative workflow · not a live patient record.</small></div></div><Link href="/health" className="nl-composer">Check shared-service status <span><ArrowRight size={18} /></span></Link></div><aside className="nl-context"><span className="nl-eyebrow">CURRENT RELEASE</span><h3 className="nl-context-title">What works today.</h3><div><MessageCircle size={18} /><span><b>Website chat</b><small>General educational Q&amp;A · early access</small></span></div><div><Leaf size={18} /><span><b>Android beta</b><small>Local meals, notes and saved conversations</small></span></div><div><FileText size={18} /><span><b>Shared health records</b><small>Not active until the private service launches</small></span></div><p>Review privacy details before sharing information. Local Android journal storage is not encrypted by NutritiScan.</p></aside></div></div>
    </section><section className="nl-bento" id="engine"><div className="nl-section-head"><span className="nl-eyebrow">AVAILABLE NOW · EARLY ACCESS</span><h2>A little less scattered.<br />A little more understood.</h2><p>Use the web chat for general health questions and the Android beta to keep personal notes together. Shared record and report tools remain unavailable in this release.</p></div><div className="nl-bento-grid">{FEATURES.map(({ icon: Icon, title, text, tag, tone }) => <article key={title} className={`nl-card nl-${tone}`}><Icon size={25} /><h3>{title}</h3><p>{text}</p><span>{tag}</span></article>)}</div></section>
    <section className="nl-how" id="how"><div className="nl-section-head"><span className="nl-eyebrow">HOW TO USE NUTRITISCAN</span><h2>Start with a question.<br />Keep your clinician involved.</h2></div><ol><li><span>01</span><h3>Ask a general question</h3><p>Use the early-access website chat for educational health information. A chat message is sent to NutritiScan’s server when you submit it.</p></li><li><span>02</span><h3>Keep notes in the Android beta</h3><p>Save meals and health notes locally on your device. NutritiScan does not encrypt this local journal, so protect access to your device.</p></li><li><span>03</span><h3>Discuss decisions with a clinician</h3><p>Use your notes to prepare questions. A qualified clinician—not the app—should interpret symptoms, lab results and treatment options.</p></li></ol></section>
    <section className="nl-faq nl-section" id="faq"><div className="nl-section-head"><span className="nl-eyebrow">NUTRITISCAN · QUICK ANSWERS</span><h2>Frequently asked questions</h2><p>Clear answers about what the current NutritiScan release can do, how it handles health notes and where clinical advice comes from.</p></div><div className="nl-faq-list">{FAQS.map(({ question, answer }) => <article key={question}><h3>{question}</h3><p>{answer}</p></article>)}</div></section>
    <section className="nl-section nl-privacy"><div><ShieldCheck size={28} /><h2>Health data needs a clear boundary.</h2><p>Android journal entries stay on your device and are not encrypted by NutritiScan. Web chat messages are sent to our server when you submit them and may be processed by a configured AI provider. The shared cloud-record service is not live in this release. NutritiScan does not use patient records for model training.</p><Link href="/privacy">Read how your data is handled <ArrowRight size={14} /></Link></div><ul className="nl-limits"><li>Educational prototype for adults 18+; clinical validation is not complete.</li><li>No diagnosis, prescribing, treatment recommendation or medication interaction check.</li><li>Emergency symptoms need urgent medical care, not a chat.</li><li>Private cloud records, report extraction and voice transcription are not active.</li><li>Review the privacy notice before sending a health-related message.</li></ul></section>
    <section className="nl-section nl-close"><span className="nl-eyebrow">WEB & ANDROID</span><h2>Your next question.<br /><em>A clearer place to start.</em></h2><div className="nl-hero-actions"><Link href="/chat" className="nl-cta nl-cta-lg">Start a conversation <ArrowRight size={17} /></Link><Link href="/health" className="nl-ghost nl-ghost-lg">Open the health dashboard</Link></div><p>Early access · local journal beta · clinician review remains essential.</p></section></main>
    <footer className="nl-footer"><Brand /><span>Built in India. Designed around your health story.</span><div><Link href="/about">About</Link><Link href="/guides/doctor-appointment-checklist">Doctor visit checklist</Link><Link href="/privacy">Privacy</Link><Link href="/terms">Terms & limitations</Link><Link href="/research">Research</Link><Link href="https://github.com/Adarsh-9182/nutritiscan/releases">Android beta</Link></div></footer>
  </div>;
}
