"use client";
import Link from "next/link";
import { Activity, ArrowRight, Check, FileText, Leaf, LockKeyhole, MessageCircle, Pill, Plus, ShieldCheck, UserRound } from "lucide-react";

export function Brand() { return <span className="ns-brand"><span className="ns-mark"><Plus size={21} strokeWidth={2.5} /></span>nutriti<span>scan</span><i>°</i></span>; }
const FEATURES = [
  { icon: MessageCircle, title: "Start with a question.", text: "The public health chat helps explain health information. The shared workspace can answer questions about confirmed records, with exact dates and sources.", tag: "Chat & record tools", tone: "lime" },
  { icon: FileText, title: "Make reports readable.", text: "Upload a PDF or a report photo to the private health service. Check the extracted names, values, units and date against the original before saving anything to your timeline.", tag: "Review before saving", tone: "plain" },
  { icon: Activity, title: "See the longer picture.", text: "Your confirmed measurements become a timeline. Known equivalent units are normalized, and every plotted point keeps its record source. Missing values stay missing.", tag: "Exact lab trends", tone: "plain" },
  { icon: Pill, title: "Keep medicines in context.", text: "Keep a patient-entered medicine and allergy history. Interaction checks and prescription changes belong with verified drug data and a pharmacist or doctor.", tag: "Clinical boundaries", tone: "plain" },
  { icon: Leaf, title: "Notice your everyday habits.", text: "The Android app keeps a local meal journal, with nutrition values you enter or confirm from a product label. Personal targets are never guessed from an invented profile.", tag: "Local nutrition journal", tone: "plain" },
  { icon: UserRound, title: "Arrive with a clearer story.", text: "Prepare a factual summary from your saved health history. Bring the sources and your questions to a clinician who can review the meaning and decide the next step.", tag: "Doctor-visit preparation", tone: "wide" },
] as const;
export default function ProductLanding() {
  return <div className="ns-marketing nl-root"><div className="nl-aurora" aria-hidden />
    <header className="nl-nav"><Link href="/" aria-label="NutritiScan home"><Brand /></Link><nav aria-label="Main navigation"><a href="#engine">Your health space</a><a href="#how">How it works</a><Link href="/privacy">Privacy</Link></nav><div className="nl-nav-actions"><Link className="nl-ghost" href="/health">Health dashboard</Link><Link className="nl-cta" href="/chat">Start a conversation <ArrowRight size={15} /></Link></div></header>
    <main><section className="nl-hero" id="top"><p className="nl-positioning">YOUR PERSONAL HEALTH COMPANION</p><span className="nl-badge"><i /> A clearer picture, one record at a time</span><h1>Your health,<br />connected by <em>a conversation.</em></h1><p>Your reports, medicines, meals and health history deserve context. NutritiScan brings the questions and the records together—so you can understand what is saved, see the source and prepare the next conversation with your doctor.</p><div className="nl-hero-actions"><Link href="/chat" className="nl-cta nl-cta-lg">Ask what’s on your mind <ArrowRight size={17} /></Link><Link href="https://github.com/Adarsh-9182/nutritiscan/releases" className="nl-ghost nl-ghost-lg">Get the Android app <ArrowRight size={16} /></Link></div><ul className="nl-trust"><li><Check size={13} /> Public chat available</li><li><FileText size={13} /> Records need your confirmation</li><li><LockKeyhole size={13} /> You choose what to share</li></ul>
    <div className="nl-preview" aria-label="How NutritiScan connects your records"><div className="nl-preview-bar"><span className="nl-dot" /><span>Your health workspace</span><span className="nl-preview-live">RECORDS · SOURCES · CONTEXT</span></div><div className="nl-preview-grid"><div className="nl-thread"><div className="nl-ask">Mera hemoglobin ka trend kya hai?</div><div className="nl-reply"><div className="nl-avatar">+</div><div><div className="nl-steps"><span>Check confirmed history</span><span>Normalize known units</span><span>Show exact measurements</span></div><p>NutritiScan reads confirmed values and collection dates from structured health memory. It can show a chart and link each point to its record. If a measurement is missing, it says so.</p><div className="nl-source"><ShieldCheck size={13} /> Your records remain the source</div><small>Workflow example · no personal health values are shown here.</small></div></div><Link href="/health" className="nl-composer">Open your shared health workspace <span><ArrowRight size={18} /></span></Link></div><aside className="nl-context"><span className="nl-eyebrow">THREE KINDS OF MEMORY</span><h3 className="nl-context-title">A history you can inspect.</h3><div><Activity size={18} /><span><b>Structured records</b><small>Measurements, dates, allergies and medicines</small></span><Check size={14} /></div><div><FileText size={18} /><span><b>Original documents</b><small>Private reports with reviewed transcriptions</small></span><Check size={14} /></div><div><MessageCircle size={18} /><span><b>Conversations</b><small>Saved questions, answers and source history</small></span><Check size={14} /></div><p>The shared workspace requires a deployed health service and explicit consent. Local Android entries are stored separately.</p></aside></div></div>
    </section><section className="nl-bento" id="engine"><div className="nl-section-head"><span className="nl-eyebrow">ONE PERSON. ONE CONNECTED STORY.</span><h2>A little less scattered.<br />A little more understood.</h2><p>Bring your questions, reports and daily habits into view. Check the saved facts, follow their sources and prepare your next conversation with a clinician.</p></div><div className="nl-bento-grid">{FEATURES.map(({ icon: Icon, title, text, tag, tone }) => <article key={title} className={`nl-card nl-${tone}`}><Icon size={25} /><h3>{title}</h3><p>{text}</p><span>{tag}</span></article>)}</div></section>
    <section className="nl-how" id="how"><div className="nl-section-head"><span className="nl-eyebrow">FROM REPORT TO CONTEXT</span><h2>Keep the source.<br />Check the details.</h2></div><ol><li><span>01</span><h3>Choose your permissions</h3><p>Sign in to a shared account and decide whether to store health records. Cloud AI processing is a separate, optional choice.</p></li><li><span>02</span><h3>Upload, then review</h3><p>The service extracts proposed measurements. You check every name, value, unit and collection date against the original before confirming.</p></li><li><span>03</span><h3>Ask with the history in view</h3><p>Retrieve exact facts and trends when you need them. Bring the summary and sources to a doctor for clinical interpretation.</p></li></ol></section>
    <section className="nl-section nl-privacy"><div><ShieldCheck size={28} /><h2>Health data needs a clear boundary.</h2><p>The public chat sends the messages you submit to the server and may use a configured AI provider. The Android journal stays on your device. Shared records use a separate account and private health service, with per-user access, encrypted health content, audit history, export and deletion. NutritiScan does not use patient records for model training.</p><Link href="/privacy">Read how your data is handled <ArrowRight size={14} /></Link></div><ul className="nl-limits"><li>Educational prototype for adults 18+; clinical validation is not complete.</li><li>No independent diagnosis, prescribing or medication changes.</li><li>Emergency symptoms need urgent medical care, not a chat.</li><li>Voice transcription requires an enabled provider and your consent.</li><li>Shared health features require backend deployment; the dashboard shows its connection status.</li></ul></section>
    <section className="nl-section nl-close"><span className="nl-eyebrow">WEB & ANDROID</span><h2>Your next question.<br /><em>A clearer place to start.</em></h2><div className="nl-hero-actions"><Link href="/chat" className="nl-cta nl-cta-lg">Start a conversation <ArrowRight size={17} /></Link><Link href="/health" className="nl-ghost nl-ghost-lg">Open the health dashboard</Link></div><p>Early access · source-linked record tools · clinician review remains essential.</p></section></main>
    <footer className="nl-footer"><Brand /><span>Built in India. Designed around your health story.</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms & limitations</Link><Link href="/research">Research</Link><Link href="https://github.com/Adarsh-9182/nutritiscan/releases">Android APK</Link></div></footer>
  </div>;
}
